# Generated by Django 4.1.5 on 2023-01-26 14:57

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.user_directory_path),
        ),
    ]
