# Generated by Django 4.1.5 on 2023-01-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (0, 'Pending')])),
                ('received_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user_profile.profile')),
                ('sent_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to='user_profile.profile')),
            ],
        ),
    ]
